### PR TITLE
Display time remaining for each item

### PR DESCRIPTION
**Pull request by UJKhokhar**
- [x] Create method to check if an item is expired 
- [x] Create helper method that displays time left for an item
- [x] Add helper to view

### CODE REVIEW

**Comment by chikamichi** [comment]
What about the last remaining day? It would display "0 day left", which is misleading and not very useful.  Maybe one could be more precise in that case, for example displaying "5 hours left", or "23 minutes left".

I used `… / 1.day` in my example. I guess you could adapt that divider depending on the intermediate result in seconds:

``` ruby
  def days_left
    remaining = (created_at - 7.days.ago).to_i

    return 0 if remaining < 0

    case remaining
    when 0..1.hour
      remaining / 1.minute
    when 1.hour..1.day
      remaining / 1.hour
    else
      remaining / 1.day
    end
  end
```

But… there's a problem with that computation: the unit of the returned valued is not consistent (minutes, hours, days). Not so handy after all!

Hopefully, Rails once again has got you covered: [distance_of_time_in_words](http://api.rubyonrails.org/classes/ActionView/Helpers/DateHelper.html#method-i-distance_of_time_in_words).

How would you use that helper to display the correct duration? You may need to implement a custom helper expecting an `Item` object, `days_left(item)`, and use both `item.days_left` and the Rails' helper in there.

**Comment by chikamichi** [comment]
As always, be sure to read my message on GitHub directly, not within your mail client, because I edited extensively.

**Comment by UJKhokhar** [comment]
I got it :)

**Comment by chikamichi** [comment]
You can review [my version of this feature](https://github.com/chikamichi/blocitoff-UJKhohkhar/commit/5f8cfbb4cb63f6d05a379c92a61b128bbfad3811).

**Pull request merged**
