### PR TITLE
User sign up

### PR DESCRIPTION
**Pull request by UJKhokhar**

### CODE REVIEW

**Comment by UJKhokhar** [comment]
Say I want to work on another feature on another branch, should I branch off of this user-sign-up branch and start working there? Or should I merge to master and branch off master?

**Comment by chikamichi** [comment]
It depends. I'll write a detailled answer asap.

**Comment by chikamichi** [comment]
Let's tell a story. The story of *A Guy Named Umar Who Wanted to Rule the Pull Request*.

## aka. The PR Quest

Umar starts his journey on the master <s>cavern</s> branch:

``` sh
git checkout master
# Yep, definitely on the master branch.
```

He creates a new topic-branch and starts hacking around, cause he needs gold to buy some new stuff (aka. features):

``` sh
git checkout -b lets-get-stuffed
# git add, git commit, git add, git commit…

# From time to time, he updates the PR quest.
git push [origin lets-get-stuffed]
```

Let's say a bunch of hard-working dwarfs have introduced some changes meanwhile, waaayy back on the master branch. Those dwarfs never show up outside of master, but hell they *do* hack like crazy.

Umar could synchronize with the dwarfs using an high-tech DWiFi (DWarf iFone item), called REBASE:

``` sh
# While still on the get-stuffed branch…
git rebase master
# Up-to-date with master!

# git add, git commit, git add, git commit…
# From time to time, Umar updates the PR Quest.
git push -f [origin lets-get-stuffed] # notice the -f, cause we used rebase
```

Umar stumbles upon an ancient wizard who lures him into looking for a powerful artefact that would help him with his quest.

---

*Hum, well, here, the book comes in two versions.*

### 1st version

In the first version of the story, Umar doesn't go back to the master <s>cavern</s> branch:

``` sh
# While still on the get-stuffed-branch…

# Probably a good idea to sync with the dwarfs first:
git rebase master

# Ok, let's look for this silly artefact.
git checkout -b hey-oh-artefact
# git add, git commit, git add, git commit…
```

Eventually, Umar finds the bloody artefact, and just keeps on seizing stuff:

``` sh
# While on hey-oh-artefact
git checkout lets-get-stuffed
git merge hey-oh-artefact
# git add, git commit, git add, git commit…
git push -f [origin lets-get-stuffed]
```

Oh My! That plate armor and badass sword look good enough. It's time to fight the PR monster, with some insights from the dwarfs (maybe):

``` sh
# While still on lets-get-stuffed
git rebase master
git push -f [origin lets-get-stuffed]
# Let's go to the GitHub Realm, taunt the PR and fight like a man of noble birth would do.
```

### 2nd version

In the second version, Umar leaves *all* his stuff in a secret cave cause it's too heavy to carry home.
He comes back to the master cavern to high-five the dwarfs, just in case, and then starts looking for this bloody artefact.

``` sh
git checkout master
git checkout -b hey-oh-artefact
# git add, git commit, git add, git commit…
```

Eventually, Umar finds the bloody artefact. It's time to come home, sync with the dwarfs, then going back to seizing some more stuff:

``` sh
# While still on hey-oh-artefact
git rebase master
git checkout lets-get-stuffed
# git add, git commit, git add, git commit…
git push [origin lets-get-stuffed]
```

Oh My! That plate armor and badass sword look good enough. It's time to fight the PR monster, with some insights from the dwarfs (maybe):

``` sh
# While still on hey-oh-artefact
git rebase master
git push -f [origin lets-get-stuffed]
# Let's go to the GitHub Realm, taunt the PR and fight like a man of noble birth would do.
```

---

Morality:

* It's up to you whether you want to branch off from the topic branch or master.
* In all cases, using `git rebase master` is a good idea, when working with a team (not your current setup, but just so that you know).
* Conflicts might happen when merging. That's ok. Fix conflicts, commit.

**Comment by chikamichi** [comment]
So, Umar eventually makes it to the GitHub Realm, and taunts the Pull Request monster (read, *you actually create a Pull Request on GitHub for your topic branch). Let's say Umar defeats the monster (read, *you merged the Pull Request on GitHub*). The news must spread!

``` sh
# While still on lets-get-stuffed -- quest is over actually!

git checkout master
git pull [origin master]
# Well, that's it!

# Let's just delete the topic branch, cause it's now part of the legend (master):
git branch -d lets-get-stuffed
```

**Comment by chikamichi** [comment]
Btw, you can create the Pull Request on GitHub at the very beginning of your journey. It doesn't matter. You can always update the PR, just like you did here, by pushing to the topic branch.

**Comment by chikamichi** [comment]
* https://www.atlassian.com/git/tutorials/
* http://git-scm.com/book/en/v1

**Comment by chikamichi** [comment]
Sooooooo… this branch is called `user-sign-up`, right? I guess most of the commits here have nothing to do with user sign-up :)

What you could do, is merge this PR (because it looks good so far), and then start creating small, focused topic-branches, with their matching PR on GitHub. One topic-branch per feature.

It's OK if a PR has only, say, one or two commits: it's more about code organization and code review.

**Comment by chikamichi** [comment]
Example. Let's say you have two topic branches:

``` sh
$ git branch
* master
feature1
feature2
```

On GitHub, you created two PR, and you're working on both features at the same time (ie. on feature1 for 2 hours, then you `git checkout feature2` and hack for another couple of hours, then you have an idea about feature1 so `git checkout feature1`, etc.). During the process, you update the PRs by running `git push` while being on feature1 and feature2.

Eventually, you are done implementing the seconde feature. You `git push`, then open GitHub, review the matching PR and confirm everything's A-OK, so you merge the PR. Now, the commits from feature2 are on origin/master. Locally, you `git checkout master`, `git pull`.

**What you want to do first before continuing your work of feature1 is:**

``` sh
git checkout feature1
git rebase master # ⇠THIS
```

Because master is up-to-date and has the commits from the now-finished feature2 topic branch, this last command will update the feature1 branch so that it contains what has been merged (feature2).

At this step, *some conflicts may occur*. It's not a problem. You'll fix them, and will resume working on feature1. Eventually, it will be finished, so you'll `git push -f` (cause you used rebase, history was modified), merge the PR on GitHub, `git checkout master`, `git pull`. Done!

**Comment by UJKhokhar** [comment]
Thank you for the thorough explanation!

**Pull request merged**
